<?php
define("NO_ERROR", 0);
define("ERROR_EMAIL_ALREADY_TAKEN", 1);
define("ERROR_USERNAME_ALREADY_TAKEN", 2);
define("ERROR_IBAN_ALREADY_TAKEN", 3);
define("ERROR_SWIFT_CODE_ALREADY_TAKEN", 4);
define("ERROR_DEBIT_CARD_CODE_ALREADY_TAKEN", 5);
define("ERROR_PERSONAL_CODE_CODE_ALREADY_TAKEN", 6);
define("ERROR_BAD_USERNAME_OR_PASSWORD", 7);
define("ERROR_SERVER", 8);
define("ERROR_BAD_API_KEY", 9);
define("ERROR_BAD_SIGNATURE", 10);